version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/#service-configuration-reference
# https://docs.docker.com/compose/gettingstarted/
# https://docs.docker.com/compose/compose-file/05-services/

# doc for volumes' drivers option (wtf is this sh**)
# https://docs.docker.com/engine/reference/commandline/volume_create/
# for linux :
# https://man7.org/linux/man-pages/man8/mount.8.html

services:

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - rugbyeuse
    #restart: unless-stopped
    env_file: .env
    volumes:
      - WordPress:/var/www/wordpress

  mariadb:
    build: requirements/mariadb
    expose:
      - "3306"
    networks:
      - rugbyeuse
    #restart: unless-stopped
    env_file: .env
    volumes:
      - DB:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    expose:
      - "9000"
    networks:
      - rugbyeuse
    #restart: unless-stopped
    env_file: .env
    volumes:
      - WordPress:/var/www/wordpress

networks:
  rugbyeuse:

# doc about bind mounts
# https://docs.docker.com/storage/bind-mounts/
# doc about volume
# https://docs.docker.com/storage/volumes/

volumes:
  DB:
    driver: local
    driver_opts:
      device: /home/mravera/data/DB_volume
      type: none
      o: bind
  WordPress:
    driver: local
    driver_opts:
      device: /home/mravera/data/WordPress_volume
      type: none
      o: bind
